// Sample values used to make preview records feel real (HubSpot-style).
export const SAMPLE = {
  contacts: {
    title: 'Maria Chen',
    subtitle: 'VP of Operations · Gulf Coast Chemical',
    initials: 'MC',
    values: {
      first_name: 'Maria',
      last_name: 'Chen',
      email: 'mchen@gulfcoastchem.com',
      phone: '(225) 555-0142',
      job_title: 'VP of Operations',
      department: 'Operations',
      linkedin_url: 'linkedin.com/in/mariachen',
      lead_status: 'Open',
      lifecycle_stage: 'Opportunity',
      contact_owner: 'Daniel Fouquet',
      last_activity_date: '2 days ago',
      next_follow_up_date: 'Jun 12, 2026',
      lead_source: 'Referral',
    },
  },
  companies: {
    title: 'Gulf Coast Chemical',
    subtitle: 'Baton Rouge, LA · Chemical Manufacturing',
    initials: 'GC',
    values: {
      company_name: 'Gulf Coast Chemical',
      domain: 'gulfcoastchem.com',
      annual_revenue: '$48M',
      employees: '320',
      city_state: 'Baton Rouge, LA',
      company_owner: 'Daniel Fouquet',
      lifecycle_stage: 'Customer',
      lead_status: 'Active',
      last_activity_date: '2 days ago',
      next_visit_date: 'Jun 18, 2026',
      customer_tier: 'Tier 1',
    },
  },
  deals: {
    title: 'Gulf Coast — SIHI Vacuum Pump Package',
    subtitle: '$84,500 · Close Jun 30, 2026',
    initials: '$',
    values: {
      deal_name: 'Gulf Coast — SIHI Vacuum Pump Package',
      amount: '$84,500',
      close_date: 'Jun 30, 2026',
      deal_stage: 'Proposal Sent',
      deal_source: 'Existing Customer',
      product_service_line: 'SIHI Vacuum',
      probability: '50%',
      forecast_category: 'Best Case',
      quote_sent_date: 'Jun 2, 2026',
    },
  },
  tasks: {
    title: 'Call Maria Chen — confirm pump selection',
    subtitle: 'Call · Due Jun 23, 2026 · High priority',
    initials: '✓',
    company: 'Gulf Coast Chemical',
    values: {
      title: 'Call Maria Chen — confirm pump selection',
      task_type: 'Call',
      status: 'Not started',
      due_date: 'Jun 23, 2026',
      priority: 'High',
      assigned_to: 'Daniel Fouquet',
      queue: 'Today’s follow-ups',
      associated_record: 'Maria Chen · Gulf Coast Chemical',
      reminder: 'Jun 23, 2026 8:00 AM',
      notes: '—',
    },
  },
  tickets: {
    title: 'Pump seal leak — Unit 4',
    subtitle: 'High priority · Opened 1 day ago',
    initials: '!',
    values: {
      ticket_name: 'Pump seal leak — Unit 4',
      pipeline: 'Support Pipeline',
      status: 'In Progress',
      priority: 'High',
      category: 'Mechanical',
      source: 'Phone',
      sla_due_date: 'Jun 6, 2026',
      resolution_notes: '—',
    },
  },
}

// Sample activity feed entries keyed by activity type.
export const SAMPLE_ACTIVITY = {
  calls: { icon: '📞', text: 'Call logged — discussed seal options', when: '2 days ago' },
  emails: { icon: '📧', text: 'Email sent — Quote follow-up', when: '3 days ago' },
  meetings: { icon: '📅', text: 'Meeting — Site walkthrough', when: '1 week ago' },
  notes: { icon: '📝', text: 'Note — Prefers Tier 1 response time', when: '1 week ago' },
  tasks: { icon: '✓', text: 'Task — Send updated pricing', when: 'Due Jun 12' },
  form_submissions: { icon: '📄', text: 'Form — Requested a quote', when: '2 weeks ago' },
  deals_created: { icon: '💰', text: 'Deal created — Vacuum Pump Package', when: '2 weeks ago' },
  ticket_updates: { icon: '🎫', text: 'Ticket updated — Status to In Progress', when: '1 day ago' },
}
